# Generated by Django 4.1.6 on 2023-03-15 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0002_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_upvotes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="upvote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_upvotes_count",
            field=models.IntegerField(default="0"),
        ),
    ]
