# Generated by Django 4.1.6 on 2023-03-16 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0003_comment_comment_upvotes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_downvotes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="downvote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
