# Generated by Django 4.1.6 on 2023-03-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_comment_comment_downvotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_depth",
            field=models.IntegerField(default=1),
        ),
    ]
