# Generated by Django 4.1.6 on 2023-03-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_comment_comment_depth"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_downvotes_count",
            field=models.IntegerField(default="0"),
        ),
    ]
