# Generated by Django 4.1.4 on 2023-01-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ("-blog_created",)},
        ),
        migrations.AddField(
            model_name="blog",
            name="blog_status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=10,
            ),
        ),
    ]
