# Generated by Django 4.1.4 on 2023-01-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="blog_body",
        ),
    ]
