# Generated by Django 4.1.4 on 2023-01-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_remove_blog_blog_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_body",
            field=models.TextField(null=True),
        ),
    ]
