# Generated by Django 4.1.4 on 2023-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_options_blog_blog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_thumbnail",
            field=models.ImageField(blank=True, upload_to="blog_thumbnails/"),
        ),
    ]
