# Generated by Django 4.1.4 on 2023-01-14 15:16

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_blog_blog_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_body",
            field=django_editorjs_fields.fields.EditorJsTextField(null=True),
        ),
    ]
