# Generated by Django 4.1.4 on 2023-01-10 07:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_blog_blog_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, upload_to="blog_thumbnails/"
            ),
        ),
    ]
