# Generated by Django 4.1.4 on 2023-01-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_blog_blog_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_category",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
