# Generated by Django 4.1.4 on 2023-01-15 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_alter_blog_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_category_foreignkey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blogs.category",
            ),
        ),
    ]
