# Generated by Django 4.1.4 on 2023-01-16 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogs", "0006_blog_blog_category_foreignkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_likes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="blog_likes_count",
            field=models.IntegerField(default="0"),
        ),
    ]
