# Generated by Django 4.1.4 on 2023-01-16 18:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                default="profile_pictures/default_profile_picture.jpg",
                upload_to="profile_pictures/",
            ),
        ),
    ]
