# Generated by Django 4.1.4 on 2023-01-16 20:12

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                default="profile_pictures/default_profile_picture.jpg",
                upload_to="profile_pictures/users",
            ),
        ),
    ]
